// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMLd_sv408BR8I_ttuw5vXYZNA0oHBU1M',
    appId: '1:1067689019153:web:ecdb004f148eb01cecaeb0',
    messagingSenderId: '1067689019153',
    projectId: 'buddynotification-e9c25',
    authDomain: 'buddynotification-e9c25.firebaseapp.com',
    storageBucket: 'buddynotification-e9c25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcpUNKE7jISISKTqdYakvjv7a-1i2oe-o',
    appId: '1:1067689019153:android:4cc884c42b8e29cfecaeb0',
    messagingSenderId: '1067689019153',
    projectId: 'buddynotification-e9c25',
    storageBucket: 'buddynotification-e9c25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMyX3gW0W5VwHIapT_9c1sIsbQMvA7Z24',
    appId: '1:1067689019153:ios:4e5f8ace55bfe950ecaeb0',
    messagingSenderId: '1067689019153',
    projectId: 'buddynotification-e9c25',
    storageBucket: 'buddynotification-e9c25.appspot.com',
    iosBundleId: 'com.example.buddyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMyX3gW0W5VwHIapT_9c1sIsbQMvA7Z24',
    appId: '1:1067689019153:ios:4e5f8ace55bfe950ecaeb0',
    messagingSenderId: '1067689019153',
    projectId: 'buddynotification-e9c25',
    storageBucket: 'buddynotification-e9c25.appspot.com',
    iosBundleId: 'com.example.buddyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMLd_sv408BR8I_ttuw5vXYZNA0oHBU1M',
    appId: '1:1067689019153:web:0a1b142a1f3c81caecaeb0',
    messagingSenderId: '1067689019153',
    projectId: 'buddynotification-e9c25',
    authDomain: 'buddynotification-e9c25.firebaseapp.com',
    storageBucket: 'buddynotification-e9c25.appspot.com',
  );

}